### ISSUE TITLE
Installer problem (ubuntu/mint)

### ISSUE THREAD

**Issue by ibrierley** [wbraswell/rperl#113]
Hi, I wanted to try rperl out for the first time, I tried running 

wget https://raw.githubusercontent.com/wbraswell/rperl/master/script/rperl_installer.sh; chmod a+x ./rperl_installer.sh; ./rperl_installer.sh

I'm running it on a Mint 20/Ubuntu on a typical local machine.

The menu runs, but whatever I choose (options 20-26), it just says "Nothing To Do On Existing Machine!" and then Section Complete...

I suspect I'm missing something obvious ?

**Comment by wbraswell** [comment]
@ibrierley 
Thank you for your interest in RPerl!
For now, please use our official Docker image for RPerl:
```docker run -it wbraswell/rperl_cpan```
