### ISSUE TITLE
About _Inline folder

### ISSUE THREAD

**Issue by ToApolytoXaos** [wbraswell/rperl#12]
Greetings @wbraswell . I could not find you online and decided to open a ticket here to get your attention. I have noticed something rather interesting in my opinion.

Since we have installed `local::lib`, shouldn't we have `_Inline` been located always inside `$HOME/perl5/` directory along with `bin`, `lib`, and `man` folders?

I'm asking because I run `rperl --help` inside `/tmp` and got the same aforementioned folder.

Should it create it to the location `rperl` got called?

Cheers.

**Comment by wbraswell** [comment]
The _Inline folder(s) are automatically created by Inline::CPP, and will always be located in the directory from which you call the `rperl` executable.  Also, if anything else triggers a call to Inline::CPP, an _Inline directory may be automatically created somewhere else.
At this time, the location of the _Inline directory is completely unrelated to the location of the local::lib install directory.
So the direct answer to your question is no, the _Inline directory will not be created inside the same local::lib install directory, unless that is where you happen to execute `rperl` from.
