### ISSUE TITLE
Failed to find `rperl` executable

### ISSUE THREAD

**Issue by trizen** [wbraswell/rperl#17]
Hello,

I just installed RPerl from CPAN (`cpanm RPerl`), but I'm not able to execute it. It dies with the following error message:

```bash
$ rperl
ERROR EEXRP00: Failed to find `rperl` executable, dying
Compilation failed in require at /usr/share/perl5/site_perl/RPerl.pm line 18.
Compilation failed in require at /usr/bin/site_perl/rperl line 5.
BEGIN failed--compilation aborted at /usr/bin/site_perl/rperl line 5.
```

Any idea?

**Comment by trizen** [comment]
After taking a look at the source code, it seems that it's looking for the `rperl` executable in the Perl `@INC`, instead of `$ENV{PATH}`.

By copying `/usr/bin/site_perl/rperl` to `/usr/share/perl5/site_perl/script/rperl` everything works fine, but the issue remains for fresh installs.

**Comment by wbraswell** [comment]
Holy cow I didn't know github could automatically close an issue by putting it in the commit message like that!
@trizen Please start over from scratch using the latest code on github and see if it fixes your issue, thanks!  :)

**Comment by trizen** [comment]
Yup. It finds the correct path to `rperl` now. Thanks for fixing this :)

```
WARNING WEXRP00: Found multiple `rperl` executables, using first located, `/usr/bin/site_perl/rperl`
```

I only have to remove `/usr/share/perl5/site_perl/script/rperl`, but as you can see in the warning message, it finds the correct path: `/usr/bin/site_perl/rperl`.

**Comment by wbraswell** [comment]
@trizen 
Awesome, I'm glad it worked!  Keep the bug reports coming, I'll fix them as fast as I can.  :)
:+1:
