### ISSUE TITLE
Improve homepage

### ISSUE THREAD

**Issue by asb-capfan** [wbraswell/rperl#30]
When opening the web site http://rperl.org/, it's a bit difficult to find out whar RPerl is.
The page's title displayed in the tab says "official home" and the only hint is "running Perl5 faster" as sub-title. 

For people not knowing anything about RPerl, this might not be enough.
Could you eventually add a key phrase to the page, e.g. something like "RPerl is a Perl (interpreter? compiler?) to run Perl scripts faster. <a href="howto">Read on how to use it and have fun!</a>"

**Comment by wbraswell** [comment]
@asb-capfan 
Thanks for the feedback!  I've updated the Welcome blurb on the homepage to include the following basic RPerl info:

You've found the official Internet home of RPerl, the optimizing compiler for the Perl 5 computer programming language.
RPerl allows your low-magic Perl 5 software to be compiled into super-fast and fully-compatible C++.
