### ISSUE TITLE
Set of Perl supported?

### ISSUE THREAD

**Issue by JJ** [wbraswell/rperl#35]
I've gone from here to rperl.org, to CPAN and back again, and I haven't found the set of restricted Perl supported by RPerl. I'm particularly interested in my evolutionary algorithm code. Will that work?

**Comment by wbraswell** [comment]
@JJ 
Full user documentation is not quite ready yet.
For now, please see the N-body application for code examples:
https://github.com/wbraswell/physicsperl/blob/master/lib/PhysicsPerl/Astro/System.pm
https://github.com/wbraswell/physicsperl/blob/master/lib/PhysicsPerl/Astro/Body.pm
Please don't hesitate to contact us with questions, we are on IRC:
irc.perl.org
#perl11

**Comment by JJ** [comment]
If would be really helpful to have even a small document with the subset of Perl that is supported. Examples don't really cut it for me. I would be quite interested in using rperl, but it's impossible to be sure if it's going to work for me or not from just that example (or set of examples). I don't think pointing to an example merits closing the issue, but well, it's your program, it's your issue.

**Comment by wbraswell** [comment]
This issue is closed because the need for user documentation is huge and obvious.  I am not dismissing your request, merely pointing out that you are about the 100th person to request it, and yet I am only 1 man working as fast as I can without being paid.  I will get the user documentation done ASAP.

**Comment by rurban** [comment]
Well, https://github.com/wbraswell/rperl/blob/master/lib/RPerl/Grammar.eyp lists the accepted rperl syntax, which is a subset of the perl5 syntax. And then add a `perlcritic --brutal` requirement to it.

**Comment by JJ** [comment]
Would it be too difficult to create a Perl script that generates a
supported_perl_subset.md that was also posted online and linked from
rperl.org? To tell you the truth, I don't even know what's the eyp format.

**Comment by wbraswell** [comment]
@JJ 
As I said, I will be releasing user documentation as soon as possible.
For future reference, it is not particularly helpful to ask an unpaid programmer "would it be too difficult to create a Perl script that does foo?"
If you are interested in helping develop RPerl and/or work on user documentation, please don't hesitate to let me know.  Otherwise, you will simply have to be patient like all of the other RPerl users.
Thanks!

**Comment by JJ** [comment]
2015-09-09 21:53 GMT+02:00 William N. Braswell, Jr. <
notifications@github.com>:

> @JJ <https://github.com/JJ>
> As I said, I will be releasing user documentation as soon as possible.
> For future reference, it is not particularly helpful to ask an unpaid
> programmer "would it be too difficult to create a Perl script that does
> foo?"
>

For future reference, that's not a request. You can assign *me* that issue
if you want, or put it in a TODO list. We are all programmers here, and
we're here to help.


> If you are interested in helping develop RPerl and/or work on user
> documentation, please don't hesitate to let me know. Otherwise, you will
> simply have to be patient like all of the other RPerl users.
> Thanks!
>
That's the reason why I have been contacting you all along. I am the
developer of the Algorithm::Evolutionary module, and would like to see how
it would work with RPerl, that is, faster.

**Comment by wbraswell** [comment]
If you would like to help with the RPerl documentation, then please start by learning about EBNF, which is the template used by RPerl's .eyp grammar file:

**Comment by 8dx** [comment]
two things:

1) i suffer when it comes to writing hard working code sometimes, but i am
much better at documenting and writing something to work with
pre-established routines than novel code generation, just throwing that out
there, i would be more than happy to donate help for that, and,

B) @JJ it may not have been a request, but the exact statement was that
it's not very helpful to ask an unpaid programmer if it would be too
difficult to do something, which is precisely what you asked, and also
precisely the truth lol.

just my ¢2
