### ISSUE TITLE
git should ignore Vim-related noise

### ISSUE THREAD

**Issue by naptastic** [wbraswell/rperl#42]
Request inclusion of the code of vim.gitignore into .gitignore.

**Comment by wbraswell** [comment]
@naptastic 
We have cycled one full year, any progress?

**Comment by naptastic** [comment]
Negative. Someone else will need to handle this. Sorry.

**Comment by wbraswell** [comment]
@naptastic 
Okay I will deny the pull request and remove your name from the pending authors list.
