### ISSUE TITLE
Learning Perl: 1.22, 1.23, 1.24, & 1.26.3 Inconsistencies

### ISSUE THREAD

**Issue by ghiknt** [wbraswell/rperl#46]
The output of the code in 1.22 

- matches the expected output for the rperl command in shown in 1.24
- does not match the expected output of the /tmp/foobar command
    - Expected

        ```
        have $foo = 33
        have $bar = 1_932
        have $baz = 58.545_454_545_454_5 
        ```
    - Actual

        ```
        have $foo = 33
        have $bar = 1932
        have $baz = 58.000000
        ```
- Does not match the sample output in 1.26.3 ( but is correct)
- Text for 1.26.3 implies that the $baz calculation is a user task: ```Modify your program by adding an extra numeric variable named $baz, set its value to $bar / $foo``` but it is already in the 1.22 code.
- The explanation in 1.2.3 does not cover the baz line except that it says the three output lines should be two with all three variables: ```and following 2 lines will display on screen (not send to paper printer) the labeled values of $foo, $bar, and $baz```

**Comment by wbraswell** [comment]
@ghiknt 
Great catch on finding these errors!

All code and documentation has been corrected in the latest Github code release over the last 4 commits (not up on CPAN yet):
https://github.com/wbraswell/rperl/commit/3ad9657b5e54618efa7c27baf3fbc0211921585d
https://github.com/wbraswell/rperl/commit/5f80bc9df7162d151300ac968d60d1860f51ca50
https://github.com/wbraswell/rperl/commit/f98068f1dde5ee9aeef92b25b5421acb47009d5e
https://github.com/wbraswell/rperl/commit/5a192ed73a96c2a96975bc3233f8efe552e40a4e

Latest Learning RPerl available here:
http://rperl.org/learning_rperl.html

Thanks again, and keep up the good work!
