### ISSUE TITLE
RPerl-1.7 tests fail with perl-5.24

### ISSUE THREAD

**Issue by bmwiedemann** [wbraswell/rperl#49]
While I got rperl to mostly work on openSUSE:Tumbleweed with perl-5.22.1
it fails to pass the tests with perl-2.24 in t/11_precompiled_sort.t (among others)
as can be seen in
https://build.opensuse.org/build/home:bmwiedemann:perl/openSUSE_Tumbleweed/x86_64/perl-RPerl/_log

steps to reproduce (when you have the osc client - e.g. easy to get on openSUSE, but also available for Debian and Fedora)
osc co home:bmwiedemann:perl/perl-RPerl
cd home:bmwiedemann:perl/perl-RPerl
osc build openSUSE_Tumbleweed

**Comment by wbraswell** [comment]
@bmwiedemann 
Thank you for your interest in RPerl!
We have released a large number of updates and bug fixes, currently I am shown that Travis-CI passes all RPerl v2.2 tests using Perl v5.24, although it is not running openSUSE.
Can you please try again using the new RPerl v2.2 which is on CPAN?

**Comment by bmwiedemann** [comment]
I updated the package to 2.2 and there are different test failures now (links+info from top still apply)

```
[  695s] t/12_parse.t ................... ok
[  697s] 
[  697s] #   Failed test 'Program or module generates without errors, yes diff check, output file blib/lib/RPerl/Algorithm.h and reference file blib/lib/RPerl/Algorithm.h.CPPOPS_CPPTYPES differ at line 11, have $diff_check_retval->{line_reference} = 
[  697s] # RPerl__Algorithm() {}
[  697s] # have $diff_check_retval->{line_generated} = 
[  697s] #     RPerl__Algorithm() {}
[  697s] # '
[  697s] #   at t/13_generate.t line 406.
...
Failed 1/13 test programs. 17/4193 subtests failed.
```

**Comment by wbraswell** [comment]
@bmwiedemann 
Do you have the prerequisite program `astyle` installed?

**Comment by bmwiedemann** [comment]
indeed that gets it past the tests. thanks.

**Comment by wbraswell** [comment]
@bmwiedemann 
Wow great!  :+1:
