### ISSUE TITLE
How about writing installation process at readme page?

### ISSUE THREAD

**Issue by yuki-kimoto** [wbraswell/rperl#50]
How about writing installation process at readme page?

Is it good to show Installation process at readme page for user to install quickly.

**Comment by kberov** [comment]
:+1:

**Comment by wbraswell** [comment]
Okay I have fixed this in RPerl v2.2 release, now the Readme file includes links for both the Installation Instructions as well as the new RPerl Installer Script!  :-)
https://github.com/wbraswell/rperl/blob/master/README.md
