### ISSUE TITLE
Remove references to rperl.org (domain gone)

### ISSUE THREAD

**Issue by fecundf** [wbraswell/rperl#68]
The master README.md links to www.rperl.org in a couple places, but that domain is no longer maintained. Perhaps replace those with links to documents already in this project, removing the external dependency. That's assuming that those pages are replicated somewhere in this repository!

Alternatively, link to copies in archive.org eg. https://web.archive.org/web/20161004014627/http://rperl.org/

(or, renew the domain!)

**Comment by JJ** [comment]
Hey, I can do that. Someone add the "hacktoberfest" label (a tee is a tee)

**Comment by wbraswell** [comment]
OOPS that was my fault, I forgot to renew the domain, it has been done and the links are now valid again, thanks for catching that!
