### ISSUE TITLE
Get Yuki Kimoto to join the effort

### ISSUE THREAD

**Issue by run4flat** [wbraswell/rperl#84]
Yuki has launched his SPVM effort. His energy should be channeled into this project. He has tons of energy! Get him onto rperl!

**Comment by run4flat** [comment]
@yuki-kimoto: I'm talking to you!

**Comment by yuki-kimoto** [comment]
I can talk to you.

**Comment by wbraswell** [comment]
@run4flat 
Thanks for the connection!  :-)

@yuki-kimoto 
I have added SPVM to the Perl11.org website, welcome to the Perl 11 family!  :-D

http://perl11.org/

I would like to invite both of you to join us in IRC on server irc.perl.org in channel #perl11 where we all hang out to discuss Perl 11 and related issues.
