### ISSUE TITLE
How to install RPerl on Windows?

### ISSUE THREAD

**Issue by asb-capfan** [wbraswell/rperl#89]
The INSTALL file (https://github.com/wbraswell/rperl/blob/master/INSTALL) states for windows:

    For Windows Users:
  
      RPerl on Windows requires Strawberry Perl v5.20 or higher.
      http://strawberryperl.com/
  
      RPerl system developers may use the Mingw64 GCC v4.8 compiler.
    The Mingw64 GCC v4.6 and older compilers are not compatible.

Once I installed Strawberry Perl, what to do next? 
Can I just install it from CPAN?

**Comment by wbraswell** [comment]
@asb-capfan 
Yes, in theory you should be able to install from CPAN.
Please let me know if you run into any problems.
